name: CI / Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    name: Build and package
    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          # build renderer/node then package without auto-publish
          npm run build
          npx electron-builder --win --x64 --publish=never

      - name: Package (macOS)
        if: matrix.os == 'macos-latest'
        env:
          # Disable automatic identity discovery in CI to allow unsigned builds by default
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          npm run build
          npx electron-builder --mac --x64 --publish=never

      - name: Package (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          npm run build
          npx electron-builder --linux --x64 --publish=never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-assets-${{ matrix.os }}
          path: |
            dist/**

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Gather dist files
        run: |
          echo "Collecting dist/** files into release_artifacts/"
          mkdir -p release_artifacts
          # find and copy all files under any dist/ directory into release_artifacts while preserving relative paths
          find . -type f -path '*/dist/*' -print0 | xargs -0 -I{} bash -c 'dest="release_artifacts/$(dirname "{}")"; mkdir -p "$dest"; cp "{}" "$dest/"'
          echo "Collected files:"
          find release_artifacts -maxdepth 3 -type f -print || true

      - name: Create Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          files: |
            release_artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
